# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
  

  # truncate all static data first if desired
  TRUNCATE_FIRST = false;
  if (TRUNCATE_FIRST) then
    Species.destroy_all

    TeamLeaderAppraisalBestStatPhrase.destroy_all
    TeamLeaderAppraisalOverallPhrase.destroy_all
    AppraisalBestStat.destroy_all
    AppraisalOverall.destroy_all

    TeamLeader.destroy_all
    Team.destroy_all
  end


# Team data

  Team.find_or_initialize_by(name: 'VALOR').update_attributes!(color: 'RED')
  Team.find_or_initialize_by(name: 'MYSTIC').update_attributes!(color: 'BLUE')
  Team.find_or_initialize_by(name: 'INSTINCT').update_attributes!(color: 'YELLOW')

  TeamLeader.find_or_initialize_by(name: 'CANDELA').update_attributes!(team_id: Team.find_by(name: 'VALOR').id)
  TeamLeader.find_or_initialize_by(name: 'BLANCHE').update_attributes!(team_id: Team.find_by(name: 'MYSTIC').id)
  TeamLeader.find_or_initialize_by(name: 'SPARK').update_attributes!(team_id: Team.find_by(name: 'INSTINCT').id)

# Appraisal data

  AppraisalOverall.find_or_initialize_by(appraisal_class: 'OVERALL_AMAZING').update_attributes!(min_total_iv: 37, max_total_iv: 45)
  AppraisalOverall.find_or_initialize_by(appraisal_class: 'OVERALL_STRONG').update_attributes!(min_total_iv: 30, max_total_iv: 36)
  AppraisalOverall.find_or_initialize_by(appraisal_class: 'OVERALL_DECENT').update_attributes!(min_total_iv: 23, max_total_iv: 29)
  AppraisalOverall.find_or_initialize_by(appraisal_class: 'OVERALL_POOR').update_attributes!(min_total_iv: 0, max_total_iv: 22)

  AppraisalBestStat.find_or_initialize_by(appraisal_class: 'BEST_STAT_AMAZING').update_attributes!(min_stat_iv: 15, max_stat_iv: 15)
  AppraisalBestStat.find_or_initialize_by(appraisal_class: 'BEST_STAT_STRONG').update_attributes!(min_stat_iv: 13, max_stat_iv: 14)
  AppraisalBestStat.find_or_initialize_by(appraisal_class: 'BEST_STAT_DECENT').update_attributes!(min_stat_iv: 8, max_stat_iv: 12)
  AppraisalBestStat.find_or_initialize_by(appraisal_class: 'BEST_STAT_POOR').update_attributes!(min_stat_iv: 0, max_stat_iv: 7)

  TeamLeaderAppraisalOverallPhrase.find_or_initialize_by(phrase: 'CANDELA_OVERALL_AMAZING').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'CANDELA').id, appraisal_overall_id: AppraisalOverall.find_by(appraisal_class: 'OVERALL_AMAZING').id)
  TeamLeaderAppraisalOverallPhrase.find_or_initialize_by(phrase: 'CANDELA_OVERALL_STRONG').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'CANDELA').id, appraisal_overall_id: AppraisalOverall.find_by(appraisal_class: 'OVERALL_STRONG').id)
  TeamLeaderAppraisalOverallPhrase.find_or_initialize_by(phrase: 'CANDELA_OVERALL_DECENT').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'CANDELA').id, appraisal_overall_id: AppraisalOverall.find_by(appraisal_class: 'OVERALL_DECENT').id)
  TeamLeaderAppraisalOverallPhrase.find_or_initialize_by(phrase: 'CANDELA_OVERALL_POOR').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'CANDELA').id, appraisal_overall_id: AppraisalOverall.find_by(appraisal_class: 'OVERALL_POOR').id)
  TeamLeaderAppraisalOverallPhrase.find_or_initialize_by(phrase: 'BLANCHE_OVERALL_AMAZING').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'BLANCHE').id, appraisal_overall_id: AppraisalOverall.find_by(appraisal_class: 'OVERALL_AMAZING').id)
  TeamLeaderAppraisalOverallPhrase.find_or_initialize_by(phrase: 'BLANCHE_OVERALL_STRONG').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'BLANCHE').id, appraisal_overall_id: AppraisalOverall.find_by(appraisal_class: 'OVERALL_STRONG').id)
  TeamLeaderAppraisalOverallPhrase.find_or_initialize_by(phrase: 'BLANCHE_OVERALL_DECENT').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'BLANCHE').id, appraisal_overall_id: AppraisalOverall.find_by(appraisal_class: 'OVERALL_DECENT').id)
  TeamLeaderAppraisalOverallPhrase.find_or_initialize_by(phrase: 'BLANCHE_OVERALL_POOR').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'BLANCHE').id, appraisal_overall_id: AppraisalOverall.find_by(appraisal_class: 'OVERALL_POOR').id)
  TeamLeaderAppraisalOverallPhrase.find_or_initialize_by(phrase: 'SPARK_OVERALL_AMAZING').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'SPARK').id, appraisal_overall_id: AppraisalOverall.find_by(appraisal_class: 'OVERALL_AMAZING').id)
  TeamLeaderAppraisalOverallPhrase.find_or_initialize_by(phrase: 'SPARK_OVERALL_STRONG').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'SPARK').id, appraisal_overall_id: AppraisalOverall.find_by(appraisal_class: 'OVERALL_STRONG').id)
  TeamLeaderAppraisalOverallPhrase.find_or_initialize_by(phrase: 'SPARK_OVERALL_DECENT').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'SPARK').id, appraisal_overall_id: AppraisalOverall.find_by(appraisal_class: 'OVERALL_DECENT').id)
  TeamLeaderAppraisalOverallPhrase.find_or_initialize_by(phrase: 'SPARK_OVERALL_POOR').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'SPARK').id, appraisal_overall_id: AppraisalOverall.find_by(appraisal_class: 'OVERALL_POOR').id)

  TeamLeaderAppraisalBestStatPhrase.find_or_initialize_by(phrase: 'CANDELA_BEST_STAT_AMAZING').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'CANDELA').id, appraisal_best_stat_id: AppraisalBestStat.find_by(appraisal_class: 'BEST_STAT_AMAZING').id)
  TeamLeaderAppraisalBestStatPhrase.find_or_initialize_by(phrase: 'CANDELA_BEST_STAT_STRONG').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'CANDELA').id, appraisal_best_stat_id: AppraisalBestStat.find_by(appraisal_class: 'BEST_STAT_STRONG').id)
  TeamLeaderAppraisalBestStatPhrase.find_or_initialize_by(phrase: 'CANDELA_BEST_STAT_DECENT').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'CANDELA').id, appraisal_best_stat_id: AppraisalBestStat.find_by(appraisal_class: 'BEST_STAT_DECENT').id)
  TeamLeaderAppraisalBestStatPhrase.find_or_initialize_by(phrase: 'CANDELA_BEST_STAT_POOR').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'CANDELA').id, appraisal_best_stat_id: AppraisalBestStat.find_by(appraisal_class: 'BEST_STAT_POOR').id)
  TeamLeaderAppraisalBestStatPhrase.find_or_initialize_by(phrase: 'BLANCHE_BEST_STAT_AMAZING').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'BLANCHE').id, appraisal_best_stat_id: AppraisalBestStat.find_by(appraisal_class: 'BEST_STAT_AMAZING').id)
  TeamLeaderAppraisalBestStatPhrase.find_or_initialize_by(phrase: 'BLANCHE_BEST_STAT_STRONG').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'BLANCHE').id, appraisal_best_stat_id: AppraisalBestStat.find_by(appraisal_class: 'BEST_STAT_STRONG').id)
  TeamLeaderAppraisalBestStatPhrase.find_or_initialize_by(phrase: 'BLANCHE_BEST_STAT_DECENT').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'BLANCHE').id, appraisal_best_stat_id: AppraisalBestStat.find_by(appraisal_class: 'BEST_STAT_DECENT').id)
  TeamLeaderAppraisalBestStatPhrase.find_or_initialize_by(phrase: 'BLANCHE_BEST_STAT_POOR').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'BLANCHE').id, appraisal_best_stat_id: AppraisalBestStat.find_by(appraisal_class: 'BEST_STAT_POOR').id)
  TeamLeaderAppraisalBestStatPhrase.find_or_initialize_by(phrase: 'SPARK_BEST_STAT_AMAZING').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'SPARK').id, appraisal_best_stat_id: AppraisalBestStat.find_by(appraisal_class: 'BEST_STAT_AMAZING').id)
  TeamLeaderAppraisalBestStatPhrase.find_or_initialize_by(phrase: 'SPARK_BEST_STAT_STRONG').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'SPARK').id, appraisal_best_stat_id: AppraisalBestStat.find_by(appraisal_class: 'BEST_STAT_STRONG').id)
  TeamLeaderAppraisalBestStatPhrase.find_or_initialize_by(phrase: 'SPARK_BEST_STAT_DECENT').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'SPARK').id, appraisal_best_stat_id: AppraisalBestStat.find_by(appraisal_class: 'BEST_STAT_DECENT').id)
  TeamLeaderAppraisalBestStatPhrase.find_or_initialize_by(phrase: 'SPARK_BEST_STAT_POOR').update_attributes!(team_leader_id: TeamLeader.find_by(name: 'SPARK').id, appraisal_best_stat_id: AppraisalBestStat.find_by(appraisal_class: 'BEST_STAT_POOR').id)

  # Species data
  Species.find_or_initialize_by(species_no: 1).update_attributes!(name: 'BULBASAUR', base_attack: 126, base_defense: 126, base_stamina: 90)
  Species.find_or_initialize_by(species_no: 2).update_attributes!(name: 'IVYSAUR', base_attack: 156, base_defense: 158, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 3).update_attributes!(name: 'VENUSAUR', base_attack: 198, base_defense: 200, base_stamina: 160)
  Species.find_or_initialize_by(species_no: 4).update_attributes!(name: 'CHARMANDER', base_attack: 128, base_defense: 108, base_stamina: 78)
  Species.find_or_initialize_by(species_no: 5).update_attributes!(name: 'CHARMELEON', base_attack: 160, base_defense: 140, base_stamina: 116)
  Species.find_or_initialize_by(species_no: 6).update_attributes!(name: 'CHARIZARD', base_attack: 212, base_defense: 182, base_stamina: 156)
  Species.find_or_initialize_by(species_no: 7).update_attributes!(name: 'SQUIRTLE', base_attack: 112, base_defense: 142, base_stamina: 88)
  Species.find_or_initialize_by(species_no: 8).update_attributes!(name: 'WARTORTLE', base_attack: 144, base_defense: 176, base_stamina: 118)
  Species.find_or_initialize_by(species_no: 9).update_attributes!(name: 'BLASTOISE', base_attack: 186, base_defense: 222, base_stamina: 158)
  Species.find_or_initialize_by(species_no: 10).update_attributes!(name: 'CATERPIE', base_attack: 62, base_defense: 66, base_stamina: 90)
  Species.find_or_initialize_by(species_no: 11).update_attributes!(name: 'METAPOD', base_attack: 56, base_defense: 86, base_stamina: 100)
  Species.find_or_initialize_by(species_no: 12).update_attributes!(name: 'BUTTERFREE', base_attack: 144, base_defense: 144, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 13).update_attributes!(name: 'WEEDLE', base_attack: 68, base_defense: 64, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 14).update_attributes!(name: 'KAKUNA', base_attack: 62, base_defense: 82, base_stamina: 90)
  Species.find_or_initialize_by(species_no: 15).update_attributes!(name: 'BEEDRILL', base_attack: 144, base_defense: 130, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 16).update_attributes!(name: 'PIDGEY', base_attack: 94, base_defense: 90, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 17).update_attributes!(name: 'PIDGEOTTO', base_attack: 126, base_defense: 122, base_stamina: 126)
  Species.find_or_initialize_by(species_no: 18).update_attributes!(name: 'PIDGEOT', base_attack: 170, base_defense: 166, base_stamina: 166)
  Species.find_or_initialize_by(species_no: 19).update_attributes!(name: 'RATTATA', base_attack: 92, base_defense: 86, base_stamina: 60)
  Species.find_or_initialize_by(species_no: 20).update_attributes!(name: 'RATICATE', base_attack: 146, base_defense: 150, base_stamina: 110)
  Species.find_or_initialize_by(species_no: 21).update_attributes!(name: 'SPEAROW', base_attack: 102, base_defense: 78, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 22).update_attributes!(name: 'FEAROW', base_attack: 168, base_defense: 146, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 23).update_attributes!(name: 'EKANS', base_attack: 112, base_defense: 112, base_stamina: 70)
  Species.find_or_initialize_by(species_no: 24).update_attributes!(name: 'ARBOK', base_attack: 166, base_defense: 166, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 25).update_attributes!(name: 'PIKACHU', base_attack: 124, base_defense: 108, base_stamina: 70)
  Species.find_or_initialize_by(species_no: 26).update_attributes!(name: 'RAICHU', base_attack: 200, base_defense: 154, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 27).update_attributes!(name: 'SANDSHREW', base_attack: 90, base_defense: 114, base_stamina: 100)
  Species.find_or_initialize_by(species_no: 28).update_attributes!(name: 'SANDSLASH', base_attack: 150, base_defense: 172, base_stamina: 150)
  Species.find_or_initialize_by(species_no: 29).update_attributes!(name: 'NIDORAN_F', base_attack: 100, base_defense: 104, base_stamina: 110)
  Species.find_or_initialize_by(species_no: 30).update_attributes!(name: 'NIDORINA', base_attack: 132, base_defense: 136, base_stamina: 140)
  Species.find_or_initialize_by(species_no: 31).update_attributes!(name: 'NIDOQUEEN', base_attack: 184, base_defense: 190, base_stamina: 180)
  Species.find_or_initialize_by(species_no: 32).update_attributes!(name: 'NIDORAN_M', base_attack: 110, base_defense: 94, base_stamina: 92)
  Species.find_or_initialize_by(species_no: 33).update_attributes!(name: 'NIDORINO', base_attack: 142, base_defense: 128, base_stamina: 122)
  Species.find_or_initialize_by(species_no: 34).update_attributes!(name: 'NIDOKING', base_attack: 204, base_defense: 170, base_stamina: 162)
  Species.find_or_initialize_by(species_no: 35).update_attributes!(name: 'CLEFAIRY', base_attack: 116, base_defense: 124, base_stamina: 140)
  Species.find_or_initialize_by(species_no: 36).update_attributes!(name: 'CLEFABLE', base_attack: 178, base_defense: 178, base_stamina: 190)
  Species.find_or_initialize_by(species_no: 37).update_attributes!(name: 'VULPIX', base_attack: 106, base_defense: 118, base_stamina: 76)
  Species.find_or_initialize_by(species_no: 38).update_attributes!(name: 'NINETALES', base_attack: 176, base_defense: 194, base_stamina: 146)
  Species.find_or_initialize_by(species_no: 39).update_attributes!(name: 'JIGGLYPUFF', base_attack: 98, base_defense: 54, base_stamina: 230)
  Species.find_or_initialize_by(species_no: 40).update_attributes!(name: 'WIGGLYTUFF', base_attack: 168, base_defense: 108, base_stamina: 280)
  Species.find_or_initialize_by(species_no: 41).update_attributes!(name: 'ZUBAT', base_attack: 88, base_defense: 90, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 42).update_attributes!(name: 'GOLBAT', base_attack: 164, base_defense: 164, base_stamina: 150)
  Species.find_or_initialize_by(species_no: 43).update_attributes!(name: 'ODDISH', base_attack: 134, base_defense: 130, base_stamina: 90)
  Species.find_or_initialize_by(species_no: 44).update_attributes!(name: 'GLOOM', base_attack: 162, base_defense: 158, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 45).update_attributes!(name: 'VILEPLUME', base_attack: 202, base_defense: 190, base_stamina: 150)
  Species.find_or_initialize_by(species_no: 46).update_attributes!(name: 'PARAS', base_attack: 122, base_defense: 120, base_stamina: 70)
  Species.find_or_initialize_by(species_no: 47).update_attributes!(name: 'PARASECT', base_attack: 162, base_defense: 170, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 48).update_attributes!(name: 'VENONAT', base_attack: 108, base_defense: 118, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 49).update_attributes!(name: 'VENOMOTH', base_attack: 172, base_defense: 154, base_stamina: 140)
  Species.find_or_initialize_by(species_no: 50).update_attributes!(name: 'DIGLETT', base_attack: 108, base_defense: 86, base_stamina: 20)
  Species.find_or_initialize_by(species_no: 51).update_attributes!(name: 'DUGTRIO', base_attack: 148, base_defense: 140, base_stamina: 70)
  Species.find_or_initialize_by(species_no: 52).update_attributes!(name: 'MEOWTH', base_attack: 104, base_defense: 94, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 53).update_attributes!(name: 'PERSIAN', base_attack: 156, base_defense: 146, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 54).update_attributes!(name: 'PSYDUCK', base_attack: 132, base_defense: 112, base_stamina: 100)
  Species.find_or_initialize_by(species_no: 55).update_attributes!(name: 'GOLDUCK', base_attack: 194, base_defense: 176, base_stamina: 160)
  Species.find_or_initialize_by(species_no: 56).update_attributes!(name: 'MANKEY', base_attack: 122, base_defense: 96, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 57).update_attributes!(name: 'PRIMEAPE', base_attack: 178, base_defense: 150, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 58).update_attributes!(name: 'GROWLITHE', base_attack: 156, base_defense: 110, base_stamina: 110)
  Species.find_or_initialize_by(species_no: 59).update_attributes!(name: 'ARCANINE', base_attack: 230, base_defense: 180, base_stamina: 180)
  Species.find_or_initialize_by(species_no: 60).update_attributes!(name: 'POLIWAG', base_attack: 108, base_defense: 98, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 61).update_attributes!(name: 'POLIWHIRL', base_attack: 132, base_defense: 132, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 62).update_attributes!(name: 'POLIWRATH', base_attack: 180, base_defense: 202, base_stamina: 180)
  Species.find_or_initialize_by(species_no: 63).update_attributes!(name: 'ABRA', base_attack: 110, base_defense: 76, base_stamina: 50)
  Species.find_or_initialize_by(species_no: 64).update_attributes!(name: 'KADABRA', base_attack: 150, base_defense: 112, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 65).update_attributes!(name: 'ALAKAZAM', base_attack: 186, base_defense: 152, base_stamina: 110)
  Species.find_or_initialize_by(species_no: 66).update_attributes!(name: 'MACHOP', base_attack: 118, base_defense: 96, base_stamina: 140)
  Species.find_or_initialize_by(species_no: 67).update_attributes!(name: 'MACHOKE', base_attack: 154, base_defense: 144, base_stamina: 160)
  Species.find_or_initialize_by(species_no: 68).update_attributes!(name: 'MACHAMP', base_attack: 198, base_defense: 180, base_stamina: 180)
  Species.find_or_initialize_by(species_no: 69).update_attributes!(name: 'BELLSPROUT', base_attack: 158, base_defense: 78, base_stamina: 100)
  Species.find_or_initialize_by(species_no: 70).update_attributes!(name: 'WEEPINBELL', base_attack: 190, base_defense: 110, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 71).update_attributes!(name: 'VICTREEBEL', base_attack: 222, base_defense: 152, base_stamina: 160)
  Species.find_or_initialize_by(species_no: 72).update_attributes!(name: 'TENTACOOL', base_attack: 106, base_defense: 136, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 73).update_attributes!(name: 'TENTACRUEL', base_attack: 170, base_defense: 196, base_stamina: 160)
  Species.find_or_initialize_by(species_no: 74).update_attributes!(name: 'GEODUDE', base_attack: 106, base_defense: 118, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 75).update_attributes!(name: 'GRAVELER', base_attack: 142, base_defense: 156, base_stamina: 110)
  Species.find_or_initialize_by(species_no: 76).update_attributes!(name: 'GOLEM', base_attack: 176, base_defense: 198, base_stamina: 160)
  Species.find_or_initialize_by(species_no: 77).update_attributes!(name: 'PONYTA', base_attack: 168, base_defense: 138, base_stamina: 100)
  Species.find_or_initialize_by(species_no: 78).update_attributes!(name: 'RAPIDASH', base_attack: 200, base_defense: 170, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 79).update_attributes!(name: 'SLOWPOKE', base_attack: 110, base_defense: 110, base_stamina: 180)
  Species.find_or_initialize_by(species_no: 80).update_attributes!(name: 'SLOWBRO', base_attack: 184, base_defense: 198, base_stamina: 190)
  Species.find_or_initialize_by(species_no: 81).update_attributes!(name: 'MAGNEMITE', base_attack: 128, base_defense: 138, base_stamina: 50)
  Species.find_or_initialize_by(species_no: 82).update_attributes!(name: 'MAGNETON', base_attack: 186, base_defense: 180, base_stamina: 100)
  Species.find_or_initialize_by(species_no: 83).update_attributes!(name: 'FARFETCHD', base_attack: 138, base_defense: 132, base_stamina: 104)
  Species.find_or_initialize_by(species_no: 84).update_attributes!(name: 'DODUO', base_attack: 126, base_defense: 96, base_stamina: 70)
  Species.find_or_initialize_by(species_no: 85).update_attributes!(name: 'DODRIO', base_attack: 182, base_defense: 150, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 86).update_attributes!(name: 'SEEL', base_attack: 104, base_defense: 138, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 87).update_attributes!(name: 'DEWGONG', base_attack: 156, base_defense: 192, base_stamina: 180)
  Species.find_or_initialize_by(species_no: 88).update_attributes!(name: 'GRIMER', base_attack: 124, base_defense: 110, base_stamina: 160)
  Species.find_or_initialize_by(species_no: 89).update_attributes!(name: 'MUK', base_attack: 180, base_defense: 188, base_stamina: 210)
  Species.find_or_initialize_by(species_no: 90).update_attributes!(name: 'SHELLDER', base_attack: 120, base_defense: 112, base_stamina: 60)
  Species.find_or_initialize_by(species_no: 91).update_attributes!(name: 'CLOYSTER', base_attack: 196, base_defense: 196, base_stamina: 100)
  Species.find_or_initialize_by(species_no: 92).update_attributes!(name: 'GASTLY', base_attack: 136, base_defense: 82, base_stamina: 60)
  Species.find_or_initialize_by(species_no: 93).update_attributes!(name: 'HAUNTER', base_attack: 172, base_defense: 118, base_stamina: 90)
  Species.find_or_initialize_by(species_no: 94).update_attributes!(name: 'GENGAR', base_attack: 204, base_defense: 156, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 95).update_attributes!(name: 'ONIX', base_attack: 90, base_defense: 186, base_stamina: 70)
  Species.find_or_initialize_by(species_no: 96).update_attributes!(name: 'DROWZEE', base_attack: 104, base_defense: 140, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 97).update_attributes!(name: 'HYPNO', base_attack: 162, base_defense: 196, base_stamina: 170)
  Species.find_or_initialize_by(species_no: 98).update_attributes!(name: 'KRABBY', base_attack: 116, base_defense: 110, base_stamina: 60)
  Species.find_or_initialize_by(species_no: 99).update_attributes!(name: 'KINGLER', base_attack: 178, base_defense: 168, base_stamina: 110)
  Species.find_or_initialize_by(species_no: 100).update_attributes!(name: 'VOLTORB', base_attack: 102, base_defense: 124, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 101).update_attributes!(name: 'ELECTRODE', base_attack: 150, base_defense: 174, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 102).update_attributes!(name: 'EXEGGCUTE', base_attack: 110, base_defense: 132, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 103).update_attributes!(name: 'EXEGGUTOR', base_attack: 232, base_defense: 164, base_stamina: 190)
  Species.find_or_initialize_by(species_no: 104).update_attributes!(name: 'CUBONE', base_attack: 102, base_defense: 150, base_stamina: 100)
  Species.find_or_initialize_by(species_no: 105).update_attributes!(name: 'MAROWAK', base_attack: 140, base_defense: 202, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 106).update_attributes!(name: 'HITMONLEE', base_attack: 148, base_defense: 172, base_stamina: 100)
  Species.find_or_initialize_by(species_no: 107).update_attributes!(name: 'HITMONCHAN', base_attack: 138, base_defense: 204, base_stamina: 100)
  Species.find_or_initialize_by(species_no: 108).update_attributes!(name: 'LICKITUNG', base_attack: 126, base_defense: 160, base_stamina: 180)
  Species.find_or_initialize_by(species_no: 109).update_attributes!(name: 'KOFFING', base_attack: 136, base_defense: 142, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 110).update_attributes!(name: 'WEEZING', base_attack: 190, base_defense: 198, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 111).update_attributes!(name: 'RHYHORN', base_attack: 110, base_defense: 116, base_stamina: 160)
  Species.find_or_initialize_by(species_no: 112).update_attributes!(name: 'RHYDON', base_attack: 166, base_defense: 160, base_stamina: 210)
  Species.find_or_initialize_by(species_no: 113).update_attributes!(name: 'CHANSEY', base_attack: 40, base_defense: 60, base_stamina: 500)
  Species.find_or_initialize_by(species_no: 114).update_attributes!(name: 'TANGELA', base_attack: 164, base_defense: 152, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 115).update_attributes!(name: 'KANGASKHAN', base_attack: 142, base_defense: 178, base_stamina: 210)
  Species.find_or_initialize_by(species_no: 116).update_attributes!(name: 'HORSEA', base_attack: 122, base_defense: 100, base_stamina: 60)
  Species.find_or_initialize_by(species_no: 117).update_attributes!(name: 'SEADRA', base_attack: 176, base_defense: 150, base_stamina: 110)
  Species.find_or_initialize_by(species_no: 118).update_attributes!(name: 'GOLDEEN', base_attack: 112, base_defense: 126, base_stamina: 90)
  Species.find_or_initialize_by(species_no: 119).update_attributes!(name: 'SEAKING', base_attack: 172, base_defense: 160, base_stamina: 160)
  Species.find_or_initialize_by(species_no: 120).update_attributes!(name: 'STARYU', base_attack: 130, base_defense: 128, base_stamina: 60)
  Species.find_or_initialize_by(species_no: 121).update_attributes!(name: 'STARMIE', base_attack: 194, base_defense: 192, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 122).update_attributes!(name: 'MR_MIME', base_attack: 154, base_defense: 196, base_stamina: 80)
  Species.find_or_initialize_by(species_no: 123).update_attributes!(name: 'SCYTHER', base_attack: 176, base_defense: 180, base_stamina: 140)
  Species.find_or_initialize_by(species_no: 124).update_attributes!(name: 'JYNX', base_attack: 172, base_defense: 134, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 125).update_attributes!(name: 'ELECTABUZZ', base_attack: 198, base_defense: 160, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 126).update_attributes!(name: 'MAGMAR', base_attack: 214, base_defense: 158, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 127).update_attributes!(name: 'PINSIR', base_attack: 184, base_defense: 186, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 128).update_attributes!(name: 'TAUROS', base_attack: 148, base_defense: 184, base_stamina: 150)
  Species.find_or_initialize_by(species_no: 129).update_attributes!(name: 'MAGIKARP', base_attack: 42, base_defense: 84, base_stamina: 40)
  Species.find_or_initialize_by(species_no: 130).update_attributes!(name: 'GYARADOS', base_attack: 192, base_defense: 196, base_stamina: 190)
  Species.find_or_initialize_by(species_no: 131).update_attributes!(name: 'LAPRAS', base_attack: 186, base_defense: 190, base_stamina: 260)
  Species.find_or_initialize_by(species_no: 132).update_attributes!(name: 'DITTO', base_attack: 110, base_defense: 110, base_stamina: 96)
  Species.find_or_initialize_by(species_no: 133).update_attributes!(name: 'EEVEE', base_attack: 114, base_defense: 128, base_stamina: 110)
  Species.find_or_initialize_by(species_no: 134).update_attributes!(name: 'VAPOREON', base_attack: 186, base_defense: 168, base_stamina: 260)
  Species.find_or_initialize_by(species_no: 135).update_attributes!(name: 'JOLTEON', base_attack: 192, base_defense: 174, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 136).update_attributes!(name: 'FLAREON', base_attack: 238, base_defense: 178, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 137).update_attributes!(name: 'PORYGON', base_attack: 156, base_defense: 158, base_stamina: 130)
  Species.find_or_initialize_by(species_no: 138).update_attributes!(name: 'OMANYTE', base_attack: 132, base_defense: 160, base_stamina: 70)
  Species.find_or_initialize_by(species_no: 139).update_attributes!(name: 'OMASTAR', base_attack: 180, base_defense: 202, base_stamina: 140)
  Species.find_or_initialize_by(species_no: 140).update_attributes!(name: 'KABUTO', base_attack: 148, base_defense: 142, base_stamina: 60)
  Species.find_or_initialize_by(species_no: 141).update_attributes!(name: 'KABUTOPS', base_attack: 190, base_defense: 190, base_stamina: 120)
  Species.find_or_initialize_by(species_no: 142).update_attributes!(name: 'AERODACTYL', base_attack: 182, base_defense: 162, base_stamina: 160)
  Species.find_or_initialize_by(species_no: 143).update_attributes!(name: 'SNORLAX', base_attack: 180, base_defense: 180, base_stamina: 320)
  Species.find_or_initialize_by(species_no: 144).update_attributes!(name: 'ARTICUNO', base_attack: 198, base_defense: 242, base_stamina: 180)
  Species.find_or_initialize_by(species_no: 145).update_attributes!(name: 'ZAPDOS', base_attack: 232, base_defense: 194, base_stamina: 180)
  Species.find_or_initialize_by(species_no: 146).update_attributes!(name: 'MOLTRES', base_attack: 242, base_defense: 194, base_stamina: 180)
  Species.find_or_initialize_by(species_no: 147).update_attributes!(name: 'DRATINI', base_attack: 128, base_defense: 110, base_stamina: 82)
  Species.find_or_initialize_by(species_no: 148).update_attributes!(name: 'DRAGONAIR', base_attack: 170, base_defense: 152, base_stamina: 122)
  Species.find_or_initialize_by(species_no: 149).update_attributes!(name: 'DRAGONITE', base_attack: 250, base_defense: 212, base_stamina: 182)
  Species.find_or_initialize_by(species_no: 150).update_attributes!(name: 'MEWTWO', base_attack: 284, base_defense: 202, base_stamina: 212)
  Species.find_or_initialize_by(species_no: 151).update_attributes!(name: 'MEW', base_attack: 220, base_defense: 220, base_stamina: 200)

  # Monster Levels data
  MonsterLevel.find_or_initialize_by(level: 1).update_attributes!(cp_multiplier: 0.094, dust_to_level_up: 200, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 1.5).update_attributes!(cp_multiplier: 0.135137431784996, dust_to_level_up: 200, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 2).update_attributes!(cp_multiplier: 0.16639787, dust_to_level_up: 200, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 2.5).update_attributes!(cp_multiplier: 0.19265091904785, dust_to_level_up: 200, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 3).update_attributes!(cp_multiplier: 0.21573247, dust_to_level_up: 400, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 3.5).update_attributes!(cp_multiplier: 0.236572661315177, dust_to_level_up: 400, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 4).update_attributes!(cp_multiplier: 0.25572005, dust_to_level_up: 400, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 4.5).update_attributes!(cp_multiplier: 0.27353038120371, dust_to_level_up: 400, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 5).update_attributes!(cp_multiplier: 0.29024988, dust_to_level_up: 600, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 5.5).update_attributes!(cp_multiplier: 0.306057377479222, dust_to_level_up: 600, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 6).update_attributes!(cp_multiplier: 0.3210876, dust_to_level_up: 600, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 6.5).update_attributes!(cp_multiplier: 0.335445036247676, dust_to_level_up: 600, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 7).update_attributes!(cp_multiplier: 0.34921268, dust_to_level_up: 800, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 7.5).update_attributes!(cp_multiplier: 0.36245775111346, dust_to_level_up: 800, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 8).update_attributes!(cp_multiplier: 0.37523559, dust_to_level_up: 800, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 8.5).update_attributes!(cp_multiplier: 0.387592406365363, dust_to_level_up: 800, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 9).update_attributes!(cp_multiplier: 0.39956728, dust_to_level_up: 1000, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 9.5).update_attributes!(cp_multiplier: 0.411193551403768, dust_to_level_up: 1000, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 10).update_attributes!(cp_multiplier: 0.42250001, dust_to_level_up: 1000, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 10.5).update_attributes!(cp_multiplier: 0.433511688330828, dust_to_level_up: 1000, candy_to_level_up: 1)
  MonsterLevel.find_or_initialize_by(level: 11).update_attributes!(cp_multiplier: 0.44310755, dust_to_level_up: 1300, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 11.5).update_attributes!(cp_multiplier: 0.453059959102438, dust_to_level_up: 1300, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 12).update_attributes!(cp_multiplier: 0.46279839, dust_to_level_up: 1300, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 12.5).update_attributes!(cp_multiplier: 0.472336083166946, dust_to_level_up: 1300, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 13).update_attributes!(cp_multiplier: 0.48168495, dust_to_level_up: 1600, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 13.5).update_attributes!(cp_multiplier: 0.490855800344055, dust_to_level_up: 1600, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 14).update_attributes!(cp_multiplier: 0.49985844, dust_to_level_up: 1600, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 14.5).update_attributes!(cp_multiplier: 0.508701765000018, dust_to_level_up: 1600, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 15).update_attributes!(cp_multiplier: 0.51739395, dust_to_level_up: 1900, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 15.5).update_attributes!(cp_multiplier: 0.52594251127999, dust_to_level_up: 1900, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 16).update_attributes!(cp_multiplier: 0.53435433, dust_to_level_up: 1900, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 16.5).update_attributes!(cp_multiplier: 0.542635767034066, dust_to_level_up: 1900, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 17).update_attributes!(cp_multiplier: 0.55079269, dust_to_level_up: 2200, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 17.5).update_attributes!(cp_multiplier: 0.558830576321962, dust_to_level_up: 2200, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 18).update_attributes!(cp_multiplier: 0.56675452, dust_to_level_up: 2200, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 18.5).update_attributes!(cp_multiplier: 0.574569153031496, dust_to_level_up: 2200, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 19).update_attributes!(cp_multiplier: 0.58227891, dust_to_level_up: 2500, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 19.5).update_attributes!(cp_multiplier: 0.589887917070428, dust_to_level_up: 2500, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 20).update_attributes!(cp_multiplier: 0.59740001, dust_to_level_up: 2500, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 20.5).update_attributes!(cp_multiplier: 0.604818813879744, dust_to_level_up: 2500, candy_to_level_up: 2)
  MonsterLevel.find_or_initialize_by(level: 21).update_attributes!(cp_multiplier: 0.61215729, dust_to_level_up: 3000, candy_to_level_up: 3)
  MonsterLevel.find_or_initialize_by(level: 21.5).update_attributes!(cp_multiplier: 0.619404111709588, dust_to_level_up: 3000, candy_to_level_up: 3)
  MonsterLevel.find_or_initialize_by(level: 22).update_attributes!(cp_multiplier: 0.62656713, dust_to_level_up: 3000, candy_to_level_up: 3)
  MonsterLevel.find_or_initialize_by(level: 22.5).update_attributes!(cp_multiplier: 0.633649172885941, dust_to_level_up: 3000, candy_to_level_up: 3)
  MonsterLevel.find_or_initialize_by(level: 23).update_attributes!(cp_multiplier: 0.64065295, dust_to_level_up: 3500, candy_to_level_up: 3)
  MonsterLevel.find_or_initialize_by(level: 23.5).update_attributes!(cp_multiplier: 0.64758096655654, dust_to_level_up: 3500, candy_to_level_up: 3)
  MonsterLevel.find_or_initialize_by(level: 24).update_attributes!(cp_multiplier: 0.65443563, dust_to_level_up: 3500, candy_to_level_up: 3)
  MonsterLevel.find_or_initialize_by(level: 24.5).update_attributes!(cp_multiplier: 0.661219252378587, dust_to_level_up: 3500, candy_to_level_up: 3)
  MonsterLevel.find_or_initialize_by(level: 25).update_attributes!(cp_multiplier: 0.667934, dust_to_level_up: 4000, candy_to_level_up: 3)
  MonsterLevel.find_or_initialize_by(level: 25.5).update_attributes!(cp_multiplier: 0.674581895887075, dust_to_level_up: 4000, candy_to_level_up: 3)
  MonsterLevel.find_or_initialize_by(level: 26).update_attributes!(cp_multiplier: 0.68116492, dust_to_level_up: 4000, candy_to_level_up: 4)
  MonsterLevel.find_or_initialize_by(level: 26.5).update_attributes!(cp_multiplier: 0.687684923595978, dust_to_level_up: 4000, candy_to_level_up: 4)
  MonsterLevel.find_or_initialize_by(level: 27).update_attributes!(cp_multiplier: 0.69414365, dust_to_level_up: 4500, candy_to_level_up: 4)
  MonsterLevel.find_or_initialize_by(level: 27.5).update_attributes!(cp_multiplier: 0.700542870021473, dust_to_level_up: 4500, candy_to_level_up: 4)
  MonsterLevel.find_or_initialize_by(level: 28).update_attributes!(cp_multiplier: 0.70688421, dust_to_level_up: 4500, candy_to_level_up: 4)
  MonsterLevel.find_or_initialize_by(level: 28.5).update_attributes!(cp_multiplier: 0.713169118968232, dust_to_level_up: 4500, candy_to_level_up: 4)
  MonsterLevel.find_or_initialize_by(level: 29).update_attributes!(cp_multiplier: 0.71939909, dust_to_level_up: 5000, candy_to_level_up: 4)
  MonsterLevel.find_or_initialize_by(level: 29.5).update_attributes!(cp_multiplier: 0.725575603638538, dust_to_level_up: 5000, candy_to_level_up: 4)
  MonsterLevel.find_or_initialize_by(level: 30).update_attributes!(cp_multiplier: 0.7317, dust_to_level_up: 5000, candy_to_level_up: 4)
  MonsterLevel.find_or_initialize_by(level: 30.5).update_attributes!(cp_multiplier: 0.737773539714322, dust_to_level_up: 5000, candy_to_level_up: 4)
  MonsterLevel.find_or_initialize_by(level: 31).update_attributes!(cp_multiplier: 0.73776948, dust_to_level_up: 6000, candy_to_level_up: 6)
  MonsterLevel.find_or_initialize_by(level: 31.5).update_attributes!(cp_multiplier: 0.740785573840211, dust_to_level_up: 6000, candy_to_level_up: 6)
  MonsterLevel.find_or_initialize_by(level: 32).update_attributes!(cp_multiplier: 0.74378943, dust_to_level_up: 6000, candy_to_level_up: 6)
  MonsterLevel.find_or_initialize_by(level: 32.5).update_attributes!(cp_multiplier: 0.746781210911218, dust_to_level_up: 6000, candy_to_level_up: 6)
  MonsterLevel.find_or_initialize_by(level: 33).update_attributes!(cp_multiplier: 0.74976104, dust_to_level_up: 7000, candy_to_level_up: 8)
  MonsterLevel.find_or_initialize_by(level: 33.5).update_attributes!(cp_multiplier: 0.752729086652151, dust_to_level_up: 7000, candy_to_level_up: 8)
  MonsterLevel.find_or_initialize_by(level: 34).update_attributes!(cp_multiplier: 0.75568551, dust_to_level_up: 7000, candy_to_level_up: 8)
  MonsterLevel.find_or_initialize_by(level: 34.5).update_attributes!(cp_multiplier: 0.758630378256935, dust_to_level_up: 7000, candy_to_level_up: 8)
  MonsterLevel.find_or_initialize_by(level: 35).update_attributes!(cp_multiplier: 0.76156384, dust_to_level_up: 8000, candy_to_level_up: 10)
  MonsterLevel.find_or_initialize_by(level: 35.5).update_attributes!(cp_multiplier: 0.764486064742743, dust_to_level_up: 8000, candy_to_level_up: 10)
  MonsterLevel.find_or_initialize_by(level: 36).update_attributes!(cp_multiplier: 0.76739717, dust_to_level_up: 8000, candy_to_level_up: 10)
  MonsterLevel.find_or_initialize_by(level: 36.5).update_attributes!(cp_multiplier: 0.770297265550326, dust_to_level_up: 8000, candy_to_level_up: 10)
  MonsterLevel.find_or_initialize_by(level: 37).update_attributes!(cp_multiplier: 0.7731865, dust_to_level_up: 9000, candy_to_level_up: 12)
  MonsterLevel.find_or_initialize_by(level: 37.5).update_attributes!(cp_multiplier: 0.776064961567361, dust_to_level_up: 9000, candy_to_level_up: 12)
  MonsterLevel.find_or_initialize_by(level: 38).update_attributes!(cp_multiplier: 0.77893275, dust_to_level_up: 9000, candy_to_level_up: 12)
  MonsterLevel.find_or_initialize_by(level: 38.5).update_attributes!(cp_multiplier: 0.78179005481834, dust_to_level_up: 9000, candy_to_level_up: 12)
  MonsterLevel.find_or_initialize_by(level: 39).update_attributes!(cp_multiplier: 0.78463697, dust_to_level_up: 10000, candy_to_level_up: 15)
  MonsterLevel.find_or_initialize_by(level: 39.5).update_attributes!(cp_multiplier: 0.787473577639962, dust_to_level_up: 10000, candy_to_level_up: 15)
  MonsterLevel.find_or_initialize_by(level: 40).update_attributes!(cp_multiplier: 0.79030001, dust_to_level_up: 10000, candy_to_level_up: 15)
  MonsterLevel.find_or_initialize_by(level: 40.5).update_attributes!(cp_multiplier: 0.793116363843478, dust_to_level_up: nil, candy_to_level_up: nil)

  # Trainer Levels data
  TrainerLevel.find_or_initialize_by(level: 1).update_attributes!(total_xp: 0, xp_to_next_level: 1000)
  TrainerLevel.find_or_initialize_by(level: 2).update_attributes!(total_xp: 1000, xp_to_next_level: 2000)
  TrainerLevel.find_or_initialize_by(level: 3).update_attributes!(total_xp: 3000, xp_to_next_level: 3000)
  TrainerLevel.find_or_initialize_by(level: 4).update_attributes!(total_xp: 6000, xp_to_next_level: 4000)
  TrainerLevel.find_or_initialize_by(level: 5).update_attributes!(total_xp: 10000, xp_to_next_level: 5000)
  TrainerLevel.find_or_initialize_by(level: 6).update_attributes!(total_xp: 15000, xp_to_next_level: 6000)
  TrainerLevel.find_or_initialize_by(level: 7).update_attributes!(total_xp: 21000, xp_to_next_level: 7000)
  TrainerLevel.find_or_initialize_by(level: 8).update_attributes!(total_xp: 28000, xp_to_next_level: 8000)
  TrainerLevel.find_or_initialize_by(level: 9).update_attributes!(total_xp: 36000, xp_to_next_level: 9000)
  TrainerLevel.find_or_initialize_by(level: 10).update_attributes!(total_xp: 45000, xp_to_next_level: 10000)
  TrainerLevel.find_or_initialize_by(level: 11).update_attributes!(total_xp: 55000, xp_to_next_level: 10000)
  TrainerLevel.find_or_initialize_by(level: 12).update_attributes!(total_xp: 65000, xp_to_next_level: 10000)
  TrainerLevel.find_or_initialize_by(level: 13).update_attributes!(total_xp: 75000, xp_to_next_level: 10000)
  TrainerLevel.find_or_initialize_by(level: 14).update_attributes!(total_xp: 85000, xp_to_next_level: 15000)
  TrainerLevel.find_or_initialize_by(level: 15).update_attributes!(total_xp: 100000, xp_to_next_level: 20000)
  TrainerLevel.find_or_initialize_by(level: 16).update_attributes!(total_xp: 120000, xp_to_next_level: 20000)
  TrainerLevel.find_or_initialize_by(level: 17).update_attributes!(total_xp: 140000, xp_to_next_level: 20000)
  TrainerLevel.find_or_initialize_by(level: 18).update_attributes!(total_xp: 160000, xp_to_next_level: 25000)
  TrainerLevel.find_or_initialize_by(level: 19).update_attributes!(total_xp: 185000, xp_to_next_level: 25000)
  TrainerLevel.find_or_initialize_by(level: 20).update_attributes!(total_xp: 210000, xp_to_next_level: 50000)
  TrainerLevel.find_or_initialize_by(level: 21).update_attributes!(total_xp: 260000, xp_to_next_level: 75000)
  TrainerLevel.find_or_initialize_by(level: 22).update_attributes!(total_xp: 335000, xp_to_next_level: 100000)
  TrainerLevel.find_or_initialize_by(level: 23).update_attributes!(total_xp: 435000, xp_to_next_level: 125000)
  TrainerLevel.find_or_initialize_by(level: 24).update_attributes!(total_xp: 560000, xp_to_next_level: 150000)
  TrainerLevel.find_or_initialize_by(level: 25).update_attributes!(total_xp: 710000, xp_to_next_level: 190000)
  TrainerLevel.find_or_initialize_by(level: 26).update_attributes!(total_xp: 900000, xp_to_next_level: 200000)
  TrainerLevel.find_or_initialize_by(level: 27).update_attributes!(total_xp: 1100000, xp_to_next_level: 250000)
  TrainerLevel.find_or_initialize_by(level: 28).update_attributes!(total_xp: 1350000, xp_to_next_level: 300000)
  TrainerLevel.find_or_initialize_by(level: 29).update_attributes!(total_xp: 1650000, xp_to_next_level: 350000)
  TrainerLevel.find_or_initialize_by(level: 30).update_attributes!(total_xp: 2000000, xp_to_next_level: 500000)
  TrainerLevel.find_or_initialize_by(level: 31).update_attributes!(total_xp: 2500000, xp_to_next_level: 500000)
  TrainerLevel.find_or_initialize_by(level: 32).update_attributes!(total_xp: 3000000, xp_to_next_level: 750000)
  TrainerLevel.find_or_initialize_by(level: 33).update_attributes!(total_xp: 3750000, xp_to_next_level: 1000000)
  TrainerLevel.find_or_initialize_by(level: 34).update_attributes!(total_xp: 4750000, xp_to_next_level: 1250000)
  TrainerLevel.find_or_initialize_by(level: 35).update_attributes!(total_xp: 6000000, xp_to_next_level: 1500000)
  TrainerLevel.find_or_initialize_by(level: 36).update_attributes!(total_xp: 7500000, xp_to_next_level: 2000000)
  TrainerLevel.find_or_initialize_by(level: 37).update_attributes!(total_xp: 9500000, xp_to_next_level: 2500000)
  TrainerLevel.find_or_initialize_by(level: 38).update_attributes!(total_xp: 12000000, xp_to_next_level: 3000000)
  TrainerLevel.find_or_initialize_by(level: 39).update_attributes!(total_xp: 15000000, xp_to_next_level: 5000000)
  TrainerLevel.find_or_initialize_by(level: 40).update_attributes!(total_xp: 20000000, xp_to_next_level: nil)

