# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# Team / Team Leader static data

  teams = Team.create(
    [{ name: 'Valor', color: 'Red'},
     { name: 'Mystic', color: 'Blue'},
     {name: 'Instinct', color: 'Yellow'}])
  
  team_leaders = TeamLeader.create(
    [{ name: 'Candela', team_id: Team.find_by(name: 'Valor').id },
     { name: 'Blanche', team_id: Team.find_by(name: 'Mystic').id },
     { name: 'Spark',   team_id: Team.find_by(name: 'Instinct').id }])

  appraisal_overall_phrases = AppraisalOverallPhrase.create(
    [{ team_leader_id: TeamLeader.find_by(name: 'Candela').id, phrase: 'Overall, your Pokemon simply amazes me. It can accomplish anything!', min_total_iv: 37, max_total_iv: 45 },
     { team_leader_id: TeamLeader.find_by(name: 'Candela').id, phrase: 'Overall, your Pokemon is a strong Pokemon. You should be proud!', min_total_iv: 30, max_total_iv: 36},
     { team_leader_id: TeamLeader.find_by(name: 'Candela').id, phrase: 'Overall, your Pokemon is a decent Pokemon', min_total_iv: 23, max_total_iv: 29},
     { team_leader_id: TeamLeader.find_by(name: 'Candela').id, phrase: 'Overall, your Pokemon may not be great in battle, but I still like it!', min_total_iv: 0, max_total_iv: 22},
     { team_leader_id: TeamLeader.find_by(name: 'Blanche').id, phrase: 'Overall, your Pokemon is a wonder! What a breathtaking Pokemon!', min_total_iv: 37, max_total_iv: 45},
     { team_leader_id: TeamLeader.find_by(name: 'Blanche').id, phrase: 'Overall, your Pokemon has certainly caught my attention.', min_total_iv: 30, max_total_iv: 36},
     { team_leader_id: TeamLeader.find_by(name: 'Blanche').id, phrase: 'Overall, your Pokemon is above average.', min_total_iv: 23, max_total_iv: 29},
     { team_leader_id: TeamLeader.find_by(name: 'Blanche').id, phrase: 'Overall, your Pokemon is not likely to make much headway in battle.', min_total_iv: 0, max_total_iv: 22},
     { team_leader_id: TeamLeader.find_by(name: 'Spark').id, phrase: 'Overall, your Pokemon looks like it can really battle with the best of them!', min_total_iv: 37, max_total_iv: 45},
     { team_leader_id: TeamLeader.find_by(name: 'Spark').id, phrase: 'Overall, your Pokemon is really strong!', min_total_iv: 30, max_total_iv: 36},
     { team_leader_id: TeamLeader.find_by(name: 'Spark').id, phrase: 'Overall, your Pokemon is pretty decent!', min_total_iv: 23, max_total_iv: 29},
     { team_leader_id: TeamLeader.find_by(name: 'Spark').id, phrase: 'Overall, your Pokemon has room for improvement as far as battling goes.', min_total_iv: 0, max_total_iv: 22}])

  appraisal_individual_phrases = AppraisalIndividualPhrase.create(
    [{ team_leader_id: TeamLeader.find_by(name: 'Candela').id, phrase: 'I\'m blown away by its stats. WOW!', min_individual_iv: 15, max_individual_iv: 15 },
     { team_leader_id: TeamLeader.find_by(name: 'Candela').id, phrase: 'It\'s got excellent stats! How exciting!', min_individual_iv: 13, max_individual_iv: 14 },
     { team_leader_id: TeamLeader.find_by(name: 'Candela').id, phrase: 'Its stats indicate that in battle, it\'ll get the job done.', min_individual_iv: 8, max_individual_iv: 12 },
     { team_leader_id: TeamLeader.find_by(name: 'Candela').id, phrase: 'Its stats don\'t point to greatness in battle.', min_individual_iv: 0, max_individual_iv: 7 },
     { team_leader_id: TeamLeader.find_by(name: 'Blanche').id, phrase: 'Its stats exceed my calculations. It\'s incredible!', min_individual_iv: 15, max_individual_iv: 15 },
     { team_leader_id: TeamLeader.find_by(name: 'Blanche').id, phrase: 'I am certainly impressed by its stats, I must say.', min_individual_iv: 13, max_individual_iv: 14 },
     { team_leader_id: TeamLeader.find_by(name: 'Blanche').id, phrase: 'Its stats are noticeably trending to the positive.', min_individual_iv: 8, max_individual_iv: 12 },
     { team_leader_id: TeamLeader.find_by(name: 'Blanche').id, phrase: 'Its stats are not out of the norm, in my estimation.', min_individual_iv: 0, max_individual_iv: 7 },
     { team_leader_id: TeamLeader.find_by(name: 'Spark').id, phrase: 'Its stats are the best I\'ve ever seen! No doubt about it!', min_individual_iv: 15, max_individual_iv: 15 },
     { team_leader_id: TeamLeader.find_by(name: 'Spark').id, phrase: 'Its stats are really strong! Impressive.', min_individual_iv: 13, max_individual_iv: 14 },
     { team_leader_id: TeamLeader.find_by(name: 'Spark').id, phrase: 'It\'s definitely got some good stats. Definitely!', min_individual_iv: 8, max_individual_iv: 12 },
     { team_leader_id: TeamLeader.find_by(name: 'Spark').id, phrase: 'Its stats are all right, but kinda basic, as far as I can see.', min_individual_iv: 0, max_individual_iv: 7 }])


# Monster static data
  
  species = Species.create(
    [ { species_no: 1, name: 'Bulbasaur' }, { species_no: 2, name: 'Ivysaur' }, { species_no: 3, name: 'Venusaur' },
      { species_no: 4, name: 'Charmander' }, { species_no: 5, name: 'Charmeleon' }, { species_no: 6, name: 'Charizard' },
      { species_no: 7, name: 'Squirtle' }, { species_no: 8, name: 'Wartortle' }, { species_no: 9, name: 'Blastoise' },
      { species_no: 10, name: 'Caterpie' }, { species_no: 11, name: 'Metapod' }, { species_no: 12, name: 'Butterfree' },
      { species_no: 13, name: 'Weedle' }, { species_no: 14, name: 'Kakuna' }, { species_no: 15, name: 'Beedrill' },
      { species_no: 16, name: 'Pidgey' }, { species_no: 17, name: 'Pidgeotto' }, { species_no: 18, name: 'Pidgeot' },
      { species_no: 19, name: 'Rattata' }, { species_no: 20, name: 'Raticate' },
      { species_no: 21, name: 'Spearow' }, { species_no: 22, name: 'Fearow' },
      { species_no: 23, name: 'Ekans' }, { species_no: 24, name: 'Arbok' },
      { species_no: 25, name: 'Pikachu' }, { species_no: 26, name: 'Raichu' },
      { species_no: 27, name: 'Sandshrew' }, { species_no: 28, name: 'Sandslash' },
      { species_no: 29, name: 'Nidoran♀' }, { species_no: 30, name: 'Nidorina' }, { species_no: 31, name: 'Nidoqueen' },
      { species_no: 32, name: 'Nidoran♂' }, { species_no: 33, name: 'Nidorino' }, { species_no: 34, name: 'Nidoking' },
      { species_no: 35, name: 'Clefairy' }, { species_no: 36, name: 'Clefable' },
      { species_no: 37, name: 'Vulpix' }, { species_no: 38, name: 'Ninetales' },
      { species_no: 39, name: 'Jigglypuff' }, { species_no: 40, name: 'Wigglytuff' },
      { species_no: 41, name: 'Zubat' }, { species_no: 42, name: 'Golbat' },
      { species_no: 43, name: 'Oddish' }, { species_no: 44, name: 'Gloom' }, { species_no: 45, name: 'Vileplume' },
      { species_no: 46, name: 'Paras' }, { species_no: 47, name: 'Parasect' },
      { species_no: 48, name: 'Venonat' }, { species_no: 49, name: 'Venomoth' },
      { species_no: 50, name: 'Diglett' }, { species_no: 51, name: 'Dugtrio' },
      { species_no: 52, name: 'Meowth' }, { species_no: 53, name: 'Persian' },
      { species_no: 54, name: 'Psyduck' }, { species_no: 55, name: 'Golduck' },
      { species_no: 56, name: 'Mankey' }, { species_no: 57, name: 'Primeape' },
      { species_no: 58, name: 'Growlithe' }, { species_no: 59, name: 'Arcanine' },
      { species_no: 60, name: 'Poliwag' }, { species_no: 61, name: 'Poliwhirl' }, { species_no: 62, name: 'Poliwrath' },
      { species_no: 63, name: 'Abra' }, { species_no: 64, name: 'Kadabra' }, { species_no: 65, name: 'Alakazam' },
      { species_no: 66, name: 'Machop' }, { species_no: 67, name: 'Machoke' }, { species_no: 68, name: 'Machamp' },
      { species_no: 69, name: 'Bellsprout' }, { species_no: 70, name: 'Weepinbell' }, { species_no: 71, name: 'Victreebel' },
      { species_no: 72, name: 'Tentacool' }, { species_no: 73, name: 'Tentacruel' },
      { species_no: 74, name: 'Geodude' }, { species_no: 75, name: 'Graveler' }, { species_no: 76, name: 'Golem' },
      { species_no: 77, name: 'Ponyta' }, { species_no: 78, name: 'Rapidash' },
      { species_no: 79, name: 'Slowpoke' }, { species_no: 80, name: 'Slowbro' },
      { species_no: 81, name: 'Magnemite' }, { species_no: 82, name: 'Magneton' },
      { species_no: 83, name: 'Farfetch\'d' },
      { species_no: 84, name: 'Doduo' }, { species_no: 85, name: 'Dodrio' },
      { species_no: 86, name: 'Seel' }, { species_no: 87, name: 'Dewgong' },
      { species_no: 88, name: 'Grimer' }, { species_no: 89, name: 'Muk' },
      { species_no: 90, name: 'Shellder' }, { species_no: 91, name: 'Cloyster' },
      { species_no: 92, name: 'Gastly' }, { species_no: 93, name: 'Haunter' }, { species_no: 94, name: 'Gengar' },
      { species_no: 95, name: 'Onix' },
      { species_no: 96, name: 'Drowzee' }, { species_no: 97, name: 'Hypno' },
      { species_no: 98, name: 'Krabby' }, { species_no: 99, name: 'Kingler' },
      { species_no: 100, name: 'Voltorb' }, { species_no: 101, name: 'Electrode' },
      { species_no: 102, name: 'Exeggcute' }, { species_no: 103, name: 'Exeggutor' },
      { species_no: 104, name: 'Cubone' }, { species_no: 105, name: 'Marowak' },
      { species_no: 106, name: 'Hitmonlee' },
      { species_no: 107, name: 'Hitmonchan' },
      { species_no: 108, name: 'Lickitung' },
      { species_no: 109, name: 'Koffing' }, { species_no: 110, name: 'Weezing' },
      { species_no: 111, name: 'Rhyhorn' }, { species_no: 112, name: 'Rhydon' },
      { species_no: 113, name: 'Chansey' },
      { species_no: 114, name: 'Tangela' },
      { species_no: 115, name: 'Kangaskhan' },
      { species_no: 116, name: 'Horsea' }, { species_no: 117, name: 'Seadra' },
      { species_no: 118, name: 'Goldeen' }, { species_no: 119, name: 'Seaking' },
      { species_no: 120, name: 'Staryu' }, { species_no: 121, name: 'Starmie' },
      { species_no: 122, name: 'Mr. Mime' },
      { species_no: 123, name: 'Scyther' },
      { species_no: 124, name: 'Jynx' },
      { species_no: 125, name: 'Electabuzz' },
      { species_no: 126, name: 'Magmar' },
      { species_no: 127, name: 'Pinsir' },
      { species_no: 128, name: 'Tauros' },
      { species_no: 129, name: 'Magikarp' }, { species_no: 130, name: 'Gyarados' },
      { species_no: 131, name: 'Lapras' },
      { species_no: 132, name: 'Ditto' },
      { species_no: 133, name: 'Eevee' }, { species_no: 134, name: 'Vaporeon' }, { species_no: 135, name: 'Jolteon' }, { species_no: 136, name: 'Flareon' },
      { species_no: 137, name: 'Porygon' },
      { species_no: 138, name: 'Omanyte' }, { species_no: 139, name: 'Omastar' },
      { species_no: 140, name: 'Kabuto' }, { species_no: 141, name: 'Kabutops' },
      { species_no: 142, name: 'Aerodactyl' },
      { species_no: 143, name: 'Snorlax' },
      { species_no: 144, name: 'Articuno' },
      { species_no: 145, name: 'Zapdos' },
      { species_no: 146, name: 'Moltres' },
      { species_no: 147, name: 'Dratini' }, { species_no: 148, name: 'Dragonair' }, { species_no: 149, name: 'Dragonite' },
      { species_no: 150, name: 'Mewtwo' },
      { species_no: 151, name: 'Mew' } ])
  
  species_base_stats = SpeciesBaseStat.create(
    [ { species_id: Species.find_by(species_no: 1).id, base_attack: 126, base_defense: 126, base_stamina: 90 }, 
      { species_id: Species.find_by(species_no: 2).id, base_attack: 156, base_defense: 158, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 3).id, base_attack: 198, base_defense: 200, base_stamina: 160 }, 
      { species_id: Species.find_by(species_no: 4).id, base_attack: 128, base_defense: 108, base_stamina: 78 }, 
      { species_id: Species.find_by(species_no: 5).id, base_attack: 160, base_defense: 140, base_stamina: 116 }, 
      { species_id: Species.find_by(species_no: 6).id, base_attack: 212, base_defense: 182, base_stamina: 156 }, 
      { species_id: Species.find_by(species_no: 7).id, base_attack: 112, base_defense: 142, base_stamina: 88 }, 
      { species_id: Species.find_by(species_no: 8).id, base_attack: 144, base_defense: 176, base_stamina: 118 }, 
      { species_id: Species.find_by(species_no: 9).id, base_attack: 186, base_defense: 222, base_stamina: 158 }, 
      { species_id: Species.find_by(species_no: 10).id, base_attack: 62, base_defense: 66, base_stamina: 90 }, 
      { species_id: Species.find_by(species_no: 11).id, base_attack: 56, base_defense: 86, base_stamina: 100 }, 
      { species_id: Species.find_by(species_no: 12).id, base_attack: 144, base_defense: 144, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 13).id, base_attack: 68, base_defense: 64, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 14).id, base_attack: 62, base_defense: 82, base_stamina: 90 }, 
      { species_id: Species.find_by(species_no: 15).id, base_attack: 144, base_defense: 130, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 16).id, base_attack: 94, base_defense: 90, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 17).id, base_attack: 126, base_defense: 122, base_stamina: 126 }, 
      { species_id: Species.find_by(species_no: 18).id, base_attack: 170, base_defense: 166, base_stamina: 166 }, 
      { species_id: Species.find_by(species_no: 19).id, base_attack: 92, base_defense: 86, base_stamina: 60 }, 
      { species_id: Species.find_by(species_no: 20).id, base_attack: 146, base_defense: 150, base_stamina: 110 }, 
      { species_id: Species.find_by(species_no: 21).id, base_attack: 102, base_defense: 78, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 22).id, base_attack: 168, base_defense: 146, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 23).id, base_attack: 112, base_defense: 112, base_stamina: 70 }, 
      { species_id: Species.find_by(species_no: 24).id, base_attack: 166, base_defense: 166, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 25).id, base_attack: 124, base_defense: 108, base_stamina: 70 }, 
      { species_id: Species.find_by(species_no: 26).id, base_attack: 200, base_defense: 154, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 27).id, base_attack: 90, base_defense: 114, base_stamina: 100 }, 
      { species_id: Species.find_by(species_no: 28).id, base_attack: 150, base_defense: 172, base_stamina: 150 }, 
      { species_id: Species.find_by(species_no: 29).id, base_attack: 100, base_defense: 104, base_stamina: 110 }, 
      { species_id: Species.find_by(species_no: 30).id, base_attack: 132, base_defense: 136, base_stamina: 140 }, 
      { species_id: Species.find_by(species_no: 31).id, base_attack: 184, base_defense: 190, base_stamina: 180 }, 
      { species_id: Species.find_by(species_no: 32).id, base_attack: 110, base_defense: 94, base_stamina: 92 }, 
      { species_id: Species.find_by(species_no: 33).id, base_attack: 142, base_defense: 128, base_stamina: 122 }, 
      { species_id: Species.find_by(species_no: 34).id, base_attack: 204, base_defense: 170, base_stamina: 162 }, 
      { species_id: Species.find_by(species_no: 35).id, base_attack: 116, base_defense: 124, base_stamina: 140 }, 
      { species_id: Species.find_by(species_no: 36).id, base_attack: 178, base_defense: 178, base_stamina: 190 }, 
      { species_id: Species.find_by(species_no: 37).id, base_attack: 106, base_defense: 118, base_stamina: 76 }, 
      { species_id: Species.find_by(species_no: 38).id, base_attack: 176, base_defense: 194, base_stamina: 146 }, 
      { species_id: Species.find_by(species_no: 39).id, base_attack: 98, base_defense: 54, base_stamina: 230 }, 
      { species_id: Species.find_by(species_no: 40).id, base_attack: 168, base_defense: 108, base_stamina: 280 }, 
      { species_id: Species.find_by(species_no: 41).id, base_attack: 88, base_defense: 90, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 42).id, base_attack: 164, base_defense: 164, base_stamina: 150 }, 
      { species_id: Species.find_by(species_no: 43).id, base_attack: 134, base_defense: 130, base_stamina: 90 }, 
      { species_id: Species.find_by(species_no: 44).id, base_attack: 162, base_defense: 158, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 45).id, base_attack: 202, base_defense: 190, base_stamina: 150 }, 
      { species_id: Species.find_by(species_no: 46).id, base_attack: 122, base_defense: 120, base_stamina: 70 }, 
      { species_id: Species.find_by(species_no: 47).id, base_attack: 162, base_defense: 170, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 48).id, base_attack: 108, base_defense: 118, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 49).id, base_attack: 172, base_defense: 154, base_stamina: 140 }, 
      { species_id: Species.find_by(species_no: 50).id, base_attack: 108, base_defense: 86, base_stamina: 20 }, 
      { species_id: Species.find_by(species_no: 51).id, base_attack: 148, base_defense: 140, base_stamina: 70 }, 
      { species_id: Species.find_by(species_no: 52).id, base_attack: 104, base_defense: 94, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 53).id, base_attack: 156, base_defense: 146, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 54).id, base_attack: 132, base_defense: 112, base_stamina: 100 }, 
      { species_id: Species.find_by(species_no: 55).id, base_attack: 194, base_defense: 176, base_stamina: 160 }, 
      { species_id: Species.find_by(species_no: 56).id, base_attack: 122, base_defense: 96, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 57).id, base_attack: 178, base_defense: 150, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 58).id, base_attack: 156, base_defense: 110, base_stamina: 110 }, 
      { species_id: Species.find_by(species_no: 59).id, base_attack: 230, base_defense: 180, base_stamina: 180 }, 
      { species_id: Species.find_by(species_no: 60).id, base_attack: 108, base_defense: 98, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 61).id, base_attack: 132, base_defense: 132, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 62).id, base_attack: 180, base_defense: 202, base_stamina: 180 }, 
      { species_id: Species.find_by(species_no: 63).id, base_attack: 110, base_defense: 76, base_stamina: 50 }, 
      { species_id: Species.find_by(species_no: 64).id, base_attack: 150, base_defense: 112, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 65).id, base_attack: 186, base_defense: 152, base_stamina: 110 }, 
      { species_id: Species.find_by(species_no: 66).id, base_attack: 118, base_defense: 96, base_stamina: 140 }, 
      { species_id: Species.find_by(species_no: 67).id, base_attack: 154, base_defense: 144, base_stamina: 160 }, 
      { species_id: Species.find_by(species_no: 68).id, base_attack: 198, base_defense: 180, base_stamina: 180 }, 
      { species_id: Species.find_by(species_no: 69).id, base_attack: 158, base_defense: 78, base_stamina: 100 }, 
      { species_id: Species.find_by(species_no: 70).id, base_attack: 190, base_defense: 110, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 71).id, base_attack: 222, base_defense: 152, base_stamina: 160 }, 
      { species_id: Species.find_by(species_no: 72).id, base_attack: 106, base_defense: 136, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 73).id, base_attack: 170, base_defense: 196, base_stamina: 160 }, 
      { species_id: Species.find_by(species_no: 74).id, base_attack: 106, base_defense: 118, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 75).id, base_attack: 142, base_defense: 156, base_stamina: 110 }, 
      { species_id: Species.find_by(species_no: 76).id, base_attack: 176, base_defense: 198, base_stamina: 160 }, 
      { species_id: Species.find_by(species_no: 77).id, base_attack: 168, base_defense: 138, base_stamina: 100 }, 
      { species_id: Species.find_by(species_no: 78).id, base_attack: 200, base_defense: 170, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 79).id, base_attack: 110, base_defense: 110, base_stamina: 180 }, 
      { species_id: Species.find_by(species_no: 80).id, base_attack: 184, base_defense: 198, base_stamina: 190 }, 
      { species_id: Species.find_by(species_no: 81).id, base_attack: 128, base_defense: 138, base_stamina: 50 }, 
      { species_id: Species.find_by(species_no: 82).id, base_attack: 186, base_defense: 180, base_stamina: 100 }, 
      { species_id: Species.find_by(species_no: 83).id, base_attack: 138, base_defense: 132, base_stamina: 104 }, 
      { species_id: Species.find_by(species_no: 84).id, base_attack: 126, base_defense: 96, base_stamina: 70 }, 
      { species_id: Species.find_by(species_no: 85).id, base_attack: 182, base_defense: 150, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 86).id, base_attack: 104, base_defense: 138, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 87).id, base_attack: 156, base_defense: 192, base_stamina: 180 }, 
      { species_id: Species.find_by(species_no: 88).id, base_attack: 124, base_defense: 110, base_stamina: 160 }, 
      { species_id: Species.find_by(species_no: 89).id, base_attack: 180, base_defense: 188, base_stamina: 210 }, 
      { species_id: Species.find_by(species_no: 90).id, base_attack: 120, base_defense: 112, base_stamina: 60 }, 
      { species_id: Species.find_by(species_no: 91).id, base_attack: 196, base_defense: 196, base_stamina: 100 }, 
      { species_id: Species.find_by(species_no: 92).id, base_attack: 136, base_defense: 82, base_stamina: 60 }, 
      { species_id: Species.find_by(species_no: 93).id, base_attack: 172, base_defense: 118, base_stamina: 90 }, 
      { species_id: Species.find_by(species_no: 94).id, base_attack: 204, base_defense: 156, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 95).id, base_attack: 90, base_defense: 186, base_stamina: 70 }, 
      { species_id: Species.find_by(species_no: 96).id, base_attack: 104, base_defense: 140, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 97).id, base_attack: 162, base_defense: 196, base_stamina: 170 }, 
      { species_id: Species.find_by(species_no: 98).id, base_attack: 116, base_defense: 110, base_stamina: 60 }, 
      { species_id: Species.find_by(species_no: 99).id, base_attack: 178, base_defense: 168, base_stamina: 110 }, 
      { species_id: Species.find_by(species_no: 100).id, base_attack: 102, base_defense: 124, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 101).id, base_attack: 150, base_defense: 174, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 102).id, base_attack: 110, base_defense: 132, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 103).id, base_attack: 232, base_defense: 164, base_stamina: 190 }, 
      { species_id: Species.find_by(species_no: 104).id, base_attack: 102, base_defense: 150, base_stamina: 100 }, 
      { species_id: Species.find_by(species_no: 105).id, base_attack: 140, base_defense: 202, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 106).id, base_attack: 148, base_defense: 172, base_stamina: 100 }, 
      { species_id: Species.find_by(species_no: 107).id, base_attack: 138, base_defense: 204, base_stamina: 100 }, 
      { species_id: Species.find_by(species_no: 108).id, base_attack: 126, base_defense: 160, base_stamina: 180 }, 
      { species_id: Species.find_by(species_no: 109).id, base_attack: 136, base_defense: 142, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 110).id, base_attack: 190, base_defense: 198, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 111).id, base_attack: 110, base_defense: 116, base_stamina: 160 }, 
      { species_id: Species.find_by(species_no: 112).id, base_attack: 166, base_defense: 160, base_stamina: 210 }, 
      { species_id: Species.find_by(species_no: 113).id, base_attack: 40, base_defense: 60, base_stamina: 500 }, 
      { species_id: Species.find_by(species_no: 114).id, base_attack: 164, base_defense: 152, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 115).id, base_attack: 142, base_defense: 178, base_stamina: 210 }, 
      { species_id: Species.find_by(species_no: 116).id, base_attack: 122, base_defense: 100, base_stamina: 60 }, 
      { species_id: Species.find_by(species_no: 117).id, base_attack: 176, base_defense: 150, base_stamina: 110 }, 
      { species_id: Species.find_by(species_no: 118).id, base_attack: 112, base_defense: 126, base_stamina: 90 }, 
      { species_id: Species.find_by(species_no: 119).id, base_attack: 172, base_defense: 160, base_stamina: 160 }, 
      { species_id: Species.find_by(species_no: 120).id, base_attack: 130, base_defense: 128, base_stamina: 60 }, 
      { species_id: Species.find_by(species_no: 121).id, base_attack: 194, base_defense: 192, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 122).id, base_attack: 154, base_defense: 196, base_stamina: 80 }, 
      { species_id: Species.find_by(species_no: 123).id, base_attack: 176, base_defense: 180, base_stamina: 140 }, 
      { species_id: Species.find_by(species_no: 124).id, base_attack: 172, base_defense: 134, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 125).id, base_attack: 198, base_defense: 160, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 126).id, base_attack: 214, base_defense: 158, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 127).id, base_attack: 184, base_defense: 186, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 128).id, base_attack: 148, base_defense: 184, base_stamina: 150 }, 
      { species_id: Species.find_by(species_no: 129).id, base_attack: 42, base_defense: 84, base_stamina: 40 }, 
      { species_id: Species.find_by(species_no: 130).id, base_attack: 192, base_defense: 196, base_stamina: 190 }, 
      { species_id: Species.find_by(species_no: 131).id, base_attack: 186, base_defense: 190, base_stamina: 260 }, 
      { species_id: Species.find_by(species_no: 132).id, base_attack: 110, base_defense: 110, base_stamina: 96 }, 
      { species_id: Species.find_by(species_no: 133).id, base_attack: 114, base_defense: 128, base_stamina: 110 }, 
      { species_id: Species.find_by(species_no: 134).id, base_attack: 186, base_defense: 168, base_stamina: 260 }, 
      { species_id: Species.find_by(species_no: 135).id, base_attack: 192, base_defense: 174, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 136).id, base_attack: 238, base_defense: 178, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 137).id, base_attack: 156, base_defense: 158, base_stamina: 130 }, 
      { species_id: Species.find_by(species_no: 138).id, base_attack: 132, base_defense: 160, base_stamina: 70 }, 
      { species_id: Species.find_by(species_no: 139).id, base_attack: 180, base_defense: 202, base_stamina: 140 }, 
      { species_id: Species.find_by(species_no: 140).id, base_attack: 148, base_defense: 142, base_stamina: 60 }, 
      { species_id: Species.find_by(species_no: 141).id, base_attack: 190, base_defense: 190, base_stamina: 120 }, 
      { species_id: Species.find_by(species_no: 142).id, base_attack: 182, base_defense: 162, base_stamina: 160 }, 
      { species_id: Species.find_by(species_no: 143).id, base_attack: 180, base_defense: 180, base_stamina: 320 }, 
      { species_id: Species.find_by(species_no: 144).id, base_attack: 198, base_defense: 242, base_stamina: 180 }, 
      { species_id: Species.find_by(species_no: 145).id, base_attack: 232, base_defense: 194, base_stamina: 180 }, 
      { species_id: Species.find_by(species_no: 146).id, base_attack: 242, base_defense: 194, base_stamina: 180 }, 
      { species_id: Species.find_by(species_no: 147).id, base_attack: 128, base_defense: 110, base_stamina: 82 }, 
      { species_id: Species.find_by(species_no: 148).id, base_attack: 170, base_defense: 152, base_stamina: 122 }, 
      { species_id: Species.find_by(species_no: 149).id, base_attack: 250, base_defense: 212, base_stamina: 182 }, 
      { species_id: Species.find_by(species_no: 150).id, base_attack: 284, base_defense: 202, base_stamina: 212 }, 
      { species_id: Species.find_by(species_no: 151).id, base_attack: 220, base_defense: 220, base_stamina: 200 } ])


# Monster level data

  levels_data = LevelsDatum.create(
    [ { level: 1, cp_multiplier: 0.094, stardust_to_power_up: 200, candy_to_power_up: 1 }, 
      { level: 1.5, cp_multiplier: 0.135137431784996, stardust_to_power_up: 200, candy_to_power_up: 1 }, 
      { level: 2, cp_multiplier: 0.16639787, stardust_to_power_up: 200, candy_to_power_up: 1 }, 
      { level: 2.5, cp_multiplier: 0.19265091904785, stardust_to_power_up: 200, candy_to_power_up: 1 }, 
      { level: 3, cp_multiplier: 0.21573247, stardust_to_power_up: 400, candy_to_power_up: 1 }, 
      { level: 3.5, cp_multiplier: 0.236572661315177, stardust_to_power_up: 400, candy_to_power_up: 1 }, 
      { level: 4, cp_multiplier: 0.25572005, stardust_to_power_up: 400, candy_to_power_up: 1 }, 
      { level: 4.5, cp_multiplier: 0.27353038120371, stardust_to_power_up: 400, candy_to_power_up: 1 }, 
      { level: 5, cp_multiplier: 0.29024988, stardust_to_power_up: 600, candy_to_power_up: 1 }, 
      { level: 5.5, cp_multiplier: 0.306057377479222, stardust_to_power_up: 600, candy_to_power_up: 1 }, 
      { level: 6, cp_multiplier: 0.3210876, stardust_to_power_up: 600, candy_to_power_up: 1 }, 
      { level: 6.5, cp_multiplier: 0.335445036247676, stardust_to_power_up: 600, candy_to_power_up: 1 }, 
      { level: 7, cp_multiplier: 0.34921268, stardust_to_power_up: 800, candy_to_power_up: 1 }, 
      { level: 7.5, cp_multiplier: 0.36245775111346, stardust_to_power_up: 800, candy_to_power_up: 1 }, 
      { level: 8, cp_multiplier: 0.37523559, stardust_to_power_up: 800, candy_to_power_up: 1 }, 
      { level: 8.5, cp_multiplier: 0.387592406365363, stardust_to_power_up: 800, candy_to_power_up: 1 }, 
      { level: 9, cp_multiplier: 0.39956728, stardust_to_power_up: 1000, candy_to_power_up: 1 }, 
      { level: 9.5, cp_multiplier: 0.411193551403768, stardust_to_power_up: 1000, candy_to_power_up: 1 }, 
      { level: 10, cp_multiplier: 0.42250001, stardust_to_power_up: 1000, candy_to_power_up: 1 }, 
      { level: 10.5, cp_multiplier: 0.433511688330828, stardust_to_power_up: 1000, candy_to_power_up: 1 }, 
      { level: 11, cp_multiplier: 0.44310755, stardust_to_power_up: 1300, candy_to_power_up: 2 }, 
      { level: 11.5, cp_multiplier: 0.453059959102438, stardust_to_power_up: 1300, candy_to_power_up: 2 }, 
      { level: 12, cp_multiplier: 0.46279839, stardust_to_power_up: 1300, candy_to_power_up: 2 }, 
      { level: 12.5, cp_multiplier: 0.472336083166946, stardust_to_power_up: 1300, candy_to_power_up: 2 }, 
      { level: 13, cp_multiplier: 0.48168495, stardust_to_power_up: 1600, candy_to_power_up: 2 }, 
      { level: 13.5, cp_multiplier: 0.490855800344055, stardust_to_power_up: 1600, candy_to_power_up: 2 }, 
      { level: 14, cp_multiplier: 0.49985844, stardust_to_power_up: 1600, candy_to_power_up: 2 }, 
      { level: 14.5, cp_multiplier: 0.508701765000018, stardust_to_power_up: 1600, candy_to_power_up: 2 }, 
      { level: 15, cp_multiplier: 0.51739395, stardust_to_power_up: 1900, candy_to_power_up: 2 }, 
      { level: 15.5, cp_multiplier: 0.52594251127999, stardust_to_power_up: 1900, candy_to_power_up: 2 }, 
      { level: 16, cp_multiplier: 0.53435433, stardust_to_power_up: 1900, candy_to_power_up: 2 }, 
      { level: 16.5, cp_multiplier: 0.542635767034066, stardust_to_power_up: 1900, candy_to_power_up: 2 }, 
      { level: 17, cp_multiplier: 0.55079269, stardust_to_power_up: 2200, candy_to_power_up: 2 }, 
      { level: 17.5, cp_multiplier: 0.558830576321962, stardust_to_power_up: 2200, candy_to_power_up: 2 }, 
      { level: 18, cp_multiplier: 0.56675452, stardust_to_power_up: 2200, candy_to_power_up: 2 }, 
      { level: 18.5, cp_multiplier: 0.574569153031496, stardust_to_power_up: 2200, candy_to_power_up: 2 }, 
      { level: 19, cp_multiplier: 0.58227891, stardust_to_power_up: 2500, candy_to_power_up: 2 }, 
      { level: 19.5, cp_multiplier: 0.589887917070428, stardust_to_power_up: 2500, candy_to_power_up: 2 }, 
      { level: 20, cp_multiplier: 0.59740001, stardust_to_power_up: 2500, candy_to_power_up: 2 }, 
      { level: 20.5, cp_multiplier: 0.604818813879744, stardust_to_power_up: 2500, candy_to_power_up: 2 }, 
      { level: 21, cp_multiplier: 0.61215729, stardust_to_power_up: 3000, candy_to_power_up: 3 }, 
      { level: 21.5, cp_multiplier: 0.619404111709588, stardust_to_power_up: 3000, candy_to_power_up: 3 }, 
      { level: 22, cp_multiplier: 0.62656713, stardust_to_power_up: 3000, candy_to_power_up: 3 }, 
      { level: 22.5, cp_multiplier: 0.633649172885941, stardust_to_power_up: 3000, candy_to_power_up: 3 }, 
      { level: 23, cp_multiplier: 0.64065295, stardust_to_power_up: 3500, candy_to_power_up: 3 }, 
      { level: 23.5, cp_multiplier: 0.64758096655654, stardust_to_power_up: 3500, candy_to_power_up: 3 }, 
      { level: 24, cp_multiplier: 0.65443563, stardust_to_power_up: 3500, candy_to_power_up: 3 }, 
      { level: 24.5, cp_multiplier: 0.661219252378587, stardust_to_power_up: 3500, candy_to_power_up: 3 }, 
      { level: 25, cp_multiplier: 0.667934, stardust_to_power_up: 4000, candy_to_power_up: 3 }, 
      { level: 25.5, cp_multiplier: 0.674581895887075, stardust_to_power_up: 4000, candy_to_power_up: 3 }, 
      { level: 26, cp_multiplier: 0.68116492, stardust_to_power_up: 4000, candy_to_power_up: 4 }, 
      { level: 26.5, cp_multiplier: 0.687684923595978, stardust_to_power_up: 4000, candy_to_power_up: 4 }, 
      { level: 27, cp_multiplier: 0.69414365, stardust_to_power_up: 4500, candy_to_power_up: 4 }, 
      { level: 27.5, cp_multiplier: 0.700542870021473, stardust_to_power_up: 4500, candy_to_power_up: 4 }, 
      { level: 28, cp_multiplier: 0.70688421, stardust_to_power_up: 4500, candy_to_power_up: 4 }, 
      { level: 28.5, cp_multiplier: 0.713169118968232, stardust_to_power_up: 4500, candy_to_power_up: 4 }, 
      { level: 29, cp_multiplier: 0.71939909, stardust_to_power_up: 5000, candy_to_power_up: 4 }, 
      { level: 29.5, cp_multiplier: 0.725575603638538, stardust_to_power_up: 5000, candy_to_power_up: 4 }, 
      { level: 30, cp_multiplier: 0.7317, stardust_to_power_up: 5000, candy_to_power_up: 4 }, 
      { level: 30.5, cp_multiplier: 0.737773539714322, stardust_to_power_up: 5000, candy_to_power_up: 4 }, 
      { level: 31, cp_multiplier: 0.73776948, stardust_to_power_up: 6000, candy_to_power_up: 6 }, 
      { level: 31.5, cp_multiplier: 0.740785573840211, stardust_to_power_up: 6000, candy_to_power_up: 6 }, 
      { level: 32, cp_multiplier: 0.74378943, stardust_to_power_up: 6000, candy_to_power_up: 6 }, 
      { level: 32.5, cp_multiplier: 0.746781210911218, stardust_to_power_up: 6000, candy_to_power_up: 6 }, 
      { level: 33, cp_multiplier: 0.74976104, stardust_to_power_up: 7000, candy_to_power_up: 8 }, 
      { level: 33.5, cp_multiplier: 0.752729086652151, stardust_to_power_up: 7000, candy_to_power_up: 8 }, 
      { level: 34, cp_multiplier: 0.75568551, stardust_to_power_up: 7000, candy_to_power_up: 8 }, 
      { level: 34.5, cp_multiplier: 0.758630378256935, stardust_to_power_up: 7000, candy_to_power_up: 8 }, 
      { level: 35, cp_multiplier: 0.76156384, stardust_to_power_up: 8000, candy_to_power_up: 10 }, 
      { level: 35.5, cp_multiplier: 0.764486064742743, stardust_to_power_up: 8000, candy_to_power_up: 10 }, 
      { level: 36, cp_multiplier: 0.76739717, stardust_to_power_up: 8000, candy_to_power_up: 10 }, 
      { level: 36.5, cp_multiplier: 0.770297265550326, stardust_to_power_up: 8000, candy_to_power_up: 10 }, 
      { level: 37, cp_multiplier: 0.7731865, stardust_to_power_up: 9000, candy_to_power_up: 12 }, 
      { level: 37.5, cp_multiplier: 0.776064961567361, stardust_to_power_up: 9000, candy_to_power_up: 12 }, 
      { level: 38, cp_multiplier: 0.77893275, stardust_to_power_up: 9000, candy_to_power_up: 12 }, 
      { level: 38.5, cp_multiplier: 0.78179005481834, stardust_to_power_up: 9000, candy_to_power_up: 12 }, 
      { level: 39, cp_multiplier: 0.78463697, stardust_to_power_up: 10000, candy_to_power_up: 15 }, 
      { level: 39.5, cp_multiplier: 0.787473577639962, stardust_to_power_up: 10000, candy_to_power_up: 15 }, 
      { level: 40, cp_multiplier: 0.79030001, stardust_to_power_up: 10000, candy_to_power_up: 15 }, 
      { level: 40.5, cp_multiplier: 0.793116363843478, stardust_to_power_up: nil, candy_to_power_up: nil } ])
