# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ab3e317a0131dce70bfe536d0e96389c1afe6d24140b6284f9fd691f594162f962e6bceedbd00b324edcd12bde78521ea19160142e2bfcdf641abddc02c4ea2

test:
  secret_key_base: b8eb5f651a10fdb62c75915b0c9a44041dca0a4abfa06f1ec7c3c871421b9b29bede37c88372c9945d4f8e1f7065a8f249ad2ac3030c0749eaf4f9005904c745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
